name: mlvamaps
channels:
  - conda-forge
  - bioconda
dependencies:
  - python>=3.12
  - pip
  - setuptools>=68
  - vsearch>=2.30
  - minimap2
  - mafft
  - raxml-ng
  - epa-ng
  - numpy>=1.24
  - parasail-python>=1.3.4
  - pysam
  - regex
  - pip:
      - sassy-rs>=0.2.6
