name: mlva-seer
channels:
  - conda-forge
  - bioconda
dependencies:
  - python>=3.12
  - pip
  - setuptools>=68
  - amplirust
  - savont>=0.6.1
  - minimap2
  - pywfa>=0.5.1
  - pysam
  - pip:
      - sassy-rs>=0.2.4
